# Generated by Django 2.2 on 2019-04-13 18:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Unnamed', max_length=120)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Weight in kg')),
                ('base_exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lifting.BaseExercise')),
            ],
        ),
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=120)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reps_count', models.PositiveIntegerField(verbose_name='Repetition Count')),
                ('rest_period', models.DurationField(default=datetime.time(0, 1, 30))),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifting.Exercise')),
                ('workout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lifting.Workout')),
            ],
        ),
    ]
